sigmf/sigmf-python

sigmf/schema-meta.json
Ran into an issue when writing new sigmf-meta files. The schema would throw an error if the `core:trailing_bytes` field was set to an integer, but the field has to be an integer for some math computations, for example those in line 428 in `sigmffile.py`
=> Modified schema for metadata files, trailing bytes field should be an integer not a string

sigmf/sigmffile.py
This PR fixes a bug (#10) where the `skip_checksum` argument is incorrectly passed in the position of the `data_buffer` parameter of `set_data_file()` when creating an instance of `SigMFFile` with a pre-existing data file.
=> Bugfix: wrong parameter when initializing with data

sigmf/__init__.py, sigmf/validate.py
I have no idea how hack-ish this is, but it "doesn't crash" on neither python 3.6 (rockylinux 8.8) nor python 3.10 (ubuntu 22.04)
"fixes" #17
=> naive attempt to prevent exception with python 3.6

.gitignore, README.md, setup.py, sigmf/__init__.py, sigmf/sigmffile.py, tests/conftest.py, tests/test_archivereader.py, tests/test_sigmffile.py
- package no longer creates a dozen random sigmf files when calling `pytest`
- re-wrote Archive tests
- will fix project description and insert `README.md` into [our pypi page](https://pypi.org/project/SigMF/) once I upload new version
- incremented to `v1.1.3`
=> Packaging and Test Improvements

README.md, sigmf/sigmffile.py, sigmf/tools/wav2sigmf.py, tests/test_archivereader.py, tests/testdata.py
Fixes #27.
Currently the `SigMFFile` and `SigMFCollection` constructors allow the caller to pass in `core:version`. The README examples, tools, and tests all set this to `sigmf.__version__`, which is the version number of the Python module, not the SigMF specification.
Since this module implements SigMF v1.0.0, I've modified the constructors to always set `core:version` to `1.0.0`, ignoring any value that may have been provided by the caller.
=> Always set core:version to 1.0.0

sigmf/sigmffile.py, tests/test_sigmffile.py
Proposed fix for #25 .
One other difference I noticed between slicing and `read_samples()` that makes this slicing behavior slightly strange: a slice will not scale int8 data (or similar) to a float, while `read_samples` will. Maybe that's not a bug and get_item should return truly "raw" data, but it could be warning-worthy.
=> Change __getitem__ to handle a single item or a slice

tox.ini
After throwing a bit of eyeballing on the existing code base, 120 characters seems to be a common enough and sensible choice of maximum line length
=> project metadata: specify maximum line length for flake8/pycodestyle

README.md
This should fix rendering on PyPI and resolve #40 by using the "raw" URL for the logo hosted on GitHub. Using the URLs `https://github.com/sigmf/SigMF/blob/sigmf-v1.x/logo/sigmf_logo.png?raw=true` or `https://raw.githubusercontent.com/sigmf/SigMF/sigmf-v1.x/logo/sigmf_logo.png` should be equivalent and also work.
A maintainer can test this change by cloning this branch, building the project, and [uploading to TestPyPI](https://packaging.python.org/en/latest/guides/using-testpypi/).
=> Fix SigMF logo rendering in PyPI documentation

sigmf/schema-meta.json, sigmf/sigmffile.py, tests/test_validation.py
According to spec, core:sample_count for annotation is optional:
_The sample_count Field
The number of samples that this Segment applies to. If sample_count is not provided, it SHOULD be assumed that the annotation applies from sample_start through the end of the Dataset, in all other cases sample_count MUST be provided._
=> Fix annotation core:sample_count requirement

sigmf/sigmffile.py, tests/test_sigmffile.py, tests/testdata.py
Fixed two scenarios where SigMFFile._count_samples() failed:
1. No data_file registered: sample_count should be calculated from annotation with highest end index, not from annotation with highest start index
2. If no core:sample_count is provided in the annotation, core:sample_start should be used (sample count must at least be equal to this)
=> Fix count samples from annotations

sigmf/utils.py, tests/test_utils.py
According to ISO8601 any number of digits is permitted for fractional seconds, the issue is that Python assumes these are microsecond, and will fail if we have more than 6 digits.
In the event that we detect more that 6 digits, truncate the fractional part and pass it to datetime.
=> utils: iso8601: strip fractional seconds

sigmf/sigmffile.py, tests/conftest.py, tests/test_archivereader.py, tests/test_validation.py
See https://github.com/sigmf/sigmf-python/issues/54.
=> Validate that global core:version is present.

pyproject.toml, sigmf/__init__.py, sigmf/apps/gui.py, sigmf/archive.py, sigmf/archivereader.py, sigmf/sigmf_hash.py, sigmf/sigmffile.py, sigmf/validate.py, tests/test_archivereader.py
When opening a sigmf archive with SigMFArchiveReader(), the data file is
currently set to the full archive (including metadata).
This causes issues when writing the archive back to disk and invalidates
the metadata hash since the data_file is now a tar archive and not just
the set of samples.
To work around the issue, carry around a BytesIO buffer with the content
of the data_file and write it to the tmpdir just before saving a new
archive to disk.
=> fix data_file in SigMFArchiveReader()

sigmf/validate.py
=> delete concept of default metadata and clarify validation err

sigmf/sigmffile.py
=> always set metadata version to current implemented specification

sigmf/sigmffile.py, tests/test_sigmffile.py
Closes #44.
This also fixes a subtle bug where before the checksum would have not been checked if it was an empty string.
=> add test for bad checksum

sigmf/__init__.py, sigmf/sigmffile.py
Override not overwrite global information when creating new `SigMFFile`.
Closes #76.
Should this be the behavior for `set_collection_info` too?
```python
def set_collection_info(self, new_collection):
"""
Overwrite the collection info with a new dictionary.
"""
self._metadata[self.COLLECTION_KEY] = new_collection.copy()
```
=> override global info instead of replace on __init__

sigmf/sigmffile.py
=> Add specification version to the metadata in SigMFCollection

README.md, sigmf/apps/convert_wav.py, sigmf/utils.py, tests/test_utils.py
- Closes #87.
- Makes all `datetime` handling explicitly use UTC.
- Resolves deprecation warning that occurring in python3.12
=> datetime parsing for python 3.7 thru 3.12; fix deprecation warning

sigmf/sigmffile.py, tests/test_sigmffile.py
Implemented a good idea from @jhazentia.
=> Add __eq__ method to SigMFFile

sigmf/__init__.py
PyPi does not allow re-uploading fixed versions, so I unfortunately need to increment the patch with no changes due to a mistake during packaging `v1.2.5`.
=> increment patch for pypi

sigmf/validate.py
=> cross-platform worker estimation

sigmf/apps/convert_wav.py, sigmf/archive.py, sigmf/archivereader.py, sigmf/schema.py, sigmf/sigmf_hash.py, sigmf/sigmffile.py, sigmf/utils.py, tests/test_archive.py, tests/test_archivereader.py, tests/test_ncd.py, tests/test_sigmffile.py
pull request for issue #90. Every path coverted to pathlib. Please, test the code and warn if there is a mistake.
=> os.path converted pathlib.Path

sigmf/__init__.py, sigmf/archive.py, sigmf/archivereader.py, sigmf/schema.py, sigmf/sigmffile.py, sigmf/utils.py, sigmf/validate.py, tests/test_archivereader.py, tests/test_sigmffile.py, tests/test_validation.py
Closes #95 and addresses some `pylint` hints.
=> remove explicit use of /tmp & address pylint issues

sigmf/__init__.py, sigmf/sigmffile.py, tests/test_sigmffile.py
The function get_sigmf_filenames() does not work correctly if a file contains dots in the filename. These are interpretted as suffixes by pathlib, and a part of the filename can be removed when forming the different SigMF filenames. This fixes the problem by only considering as file extensions the canonical SigMF file extensions. Any other suffixes are treated as part of the filename and not removed.
This fixes #106.
=> Take filenames with dots into account in get_sigmf_filenames()

sigmf/schema-meta.json
haven't tested anything on the python side yet.  @daniestevez this is for you =)
=> Update sigmf schema to v1.2.5

sigmf/__init__.py, sigmf/sigmffile.py, sigmf/validate.py, tests/test_validation.py
Extensions used in SigMF metadata must be declared in the global `core:extensions` field, but the validator wasn't checking for undeclared extensions.
Added validation to ensure all extension namespaces used in the metadata are properly declared in `global:core:extensions`. The validator now:
1. Extracts declared extension namespaces from `global:core:extensions`
2. Scans through all metadata sections (global, captures, annotations) to find extension namespaces in use
3. Raises a ValidationError if any extensions are used without being declared
{
"global": {
"core:datatype": "cf32_le",
"core:version": "1.0.0"
},
"captures": [{
"core:sample_start": 0,
"foo:some_field": 123  # Using undeclared 'foo' extension
}]
}
{
"global": {
"core:datatype": "cf32_le", 
"core:version": "1.0.0", …
=> feat: validate undeclared SigMF extensions in metadata
